### PR TITLE
Use Makefile

### PR DESCRIPTION
**Pull request by AkenRoberts**
A Makefile is a handy way of "aliasing" tasks and making them easier to execute without worrying about parameters and such. They can also help with performance by checking if generated files exist and have been changed. [More info here.](https://localheinz.com/blog/2018/01/24/makefile-for-lazy-developers/)

This is a good start for our basic Composer + tests now. Figure we can add in the tree splitting, future code style checks, etc. Travis can call `make test` also, so if we want to change the test configuration, we just change the code and push instead of reconfiguring Travis.

### CODE REVIEW

**Comment by Padam87** [comment]
I have not used this before, because I usually use the IDE for these, but it is good idea.

Could this handle the subtree pushes? (https://github.com/doctrine-extensions/doctrine-extensions/blob/master/subtree-push.sh)

(EDIT: Just checked the docs, sure it can :))

**Comment by AkenRoberts** [comment]
Yep, it could either handle calling the existing bash script, or replace the bash script entirely.

I have more thoughts about the subtree release process in the future, but that's not important now.

**Comment by AkenRoberts** [comment]
I use these on my personal projects, just because I'm used to the command line for various this (hotkey to open CLI + `make test` to run tests). It's just a nice to have, especially if you're working with others and want to abstract away the specific calls behind `make test`.

**Comment by Padam87** [comment]
I think the shell script should be removed, as it becomes unnecessary.

About the subtree: I was considering https://github.com/splitsh/lite, but I'm on windows (no release) + I don't know much about go, and did not want to spend time with it yet.

**Comment by AkenRoberts** [comment]
I was going to suggest https://github.com/Symplify/MonorepoBuilder I haven't used it yet, but it piqued my interest.

**Comment by Padam87** [comment]
This might be better for us. A more complete solution. splitsh's main advantage is the speed.

**Comment by AkenRoberts** [comment]
Yep. I like that it has tools for merging `composer.json` requirements from the packages into the monorepo file and stuff like that. Good support tools for those of us who haven't run Symfony for years. 😂 

Gonna merge the Makefile now (if anything, it'll make me happy, lol). If you want to play with adding the tree split or even the Monorepo builder, go nuts. I'm diving into the extension logic right now.

**Comment by Padam87** [comment]
Great!

Sluggable is more or less what I wanted, so that can be scrutinized :) Timestampable still needs test, and a checkup.

**Pull request merged**
