### PR TITLE
Decorate mapping driver instead of replacing it

### PR DESCRIPTION
**Pull request by Padam87**

### CODE REVIEW

**Comment by Padam87** [comment]
@AkenRoberts What is your opinion about this? Obviosly needs a test for XML driver, but It should work.

**Comment by AkenRoberts** [comment]
Looks good at a glance. Decorating is definitely better than forcing annotation mapping only.

I'm concerned that hooking into Doctrine's default mapping at all will impact users. Genuinely curious if that will be a problem. Very much speculation at this point. I know that if we separated it entirely, it would have less impact but potentially other downsides.

Did I hear you say that Knp's loads metadata in a funny way that you didn't really like?

**Comment by AkenRoberts** [comment]
Looking more closely at Knp, I see that each extension's listener checks for existence of the related trait. Definitely different from what we're doing here.

What are your thoughts on listening to the `loadClassMetadata` event, and hooking into that for our extension-specific stuff? [Here's how I did it.](https://github.com/AkenRoberts/extension-concept/blob/master/src/Common/Metadata/Loader.php)

**Comment by Padam87** [comment]
I think annotations are more approchable, and definitely more customizable. I think that is the main reason behind people preferring Gedmo.

**Comment by AkenRoberts** [comment]
Oh I agree. I'm not saying we should use a different type of config, just load annotations in a different way / place.

I think the decorated `MappingDriver` is fine for now. My concerns might be unfounded, and will present themselves more clearly down the road.

**Review by AkenRoberts — APPROVED** [review]

**Pull request merged**
